version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install pytest  # Ensure pytest is installed

  build:
    commands:
      - echo "Running unit tests..."
      - python -m pytest tests/ --verbose --disable-warnings || exit 1  # Run pytest in the tests/ directory

artifacts:
  files:
    - '**/*'
